//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lecture22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int ID { get; set; }
        public string std_Name { get; set; }
        public string Course { get; set; }
        public string Faulty_name { get; set; }
        public Nullable<int> faulty_id { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
